In [10]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score
import krippendorff
from sklearn.preprocessing import OrdinalEncoder

In [11]:
zdania = pd.read_csv('polemo1_raw/zdania.tsv', sep='\t', low_memory=False)
zdania

,domain,text,super,a,e,k,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 265,Unnamed: 266,Unnamed: 267,Unnamed: 268,Unnamed: 269,Unnamed: 270,Unnamed: 271,Unnamed: 272,Unnamed: 273,Unnamed: 274
0,produkty,"Dobrze wykonany , wygodny , zamki nie chodzą c...",z_plus_m,z_plus_m,NaN,z_plus_m,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,produkty,Stanowczo odradzam zakup wersji PL aż do momen...,z_minus_m,z_minus_m,NaN,z_minus_m,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,produkty,Ciezko mi sie odniesc do tego problemu .,z_amb,z_zero,NaN,z_amb,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,produkty,Brak dostępności tarcz w akceptowalnej cenie s...,z_minus_m,z_minus_m,NaN,z_minus_m,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,produkty,W moim subiektywnym odczuciu A4 Tech XL - 750B...,z_minus_m,z_minus_m,NaN,z_minus_m,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66421,medycyna,ciemna maso a nie fotka u fotografa - a dlacze...,z_zero,z_zero,NaN,z_zero,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66422,medycyna,"Wspomagali śmy zarówno tą większą , jak i mnie...",z_zero,z_zero,NaN,z_zero,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66423,medycyna,Kompetencja oraz zaangażowanie Pana Doktora w ...,z_plus_m,z_plus_m,NaN,z_plus_m,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66424,medycyna,"Jedna analiza wymagała 40 minut , a wynik był ...",z_zero,z_zero,NaN,z_zero,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66425,medycyna,"Mam pytanie odnośnie prowadzenia ciąży , czy w...",z_zero,z_zero,z_zero,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
meta = pd.read_csv('polemo1_raw/meta.tsv', sep='\t')
meta

,domain,text,super,a,e,k
0,produkty,Mylący tytuł który sugeruje że mamy do czynien...,meta_minus_m,meta_minus_m,NaN,meta_minus_m
1,produkty,"Łóżeczko , jest śliczne wygląda bardzo masywan...",meta_plus_s,meta_amb,meta_amb,meta_plus_s
2,produkty,"Szczerze mówiąc , to telefon jest beznadziejny...",meta_minus_m,meta_minus_m,NaN,meta_minus_m
3,produkty,a ) Teleskop nadaje się najwyżej do obserwacji...,NaN,meta_minus_m,NaN,meta_minus_m
4,produkty,"Film , który zadowoli wszystkich fanów Kinga ....",meta_plus_s,meta_plus_m,meta_plus_s,meta_plus_s
...,...,...,...,...,...,...
9627,medycyna,Dziękujemy panu Doktorowi za naszego synka bo ...,meta_plus_m,meta_plus_m,NaN,meta_plus_m
9628,medycyna,W czasie wizyty spotkał em się z dużą życzliwo...,meta_plus_m,meta_plus_m,meta_plus_m,NaN
9629,medycyna,Jestem bardzo zadowolona z zabiegu biopsji mam...,meta_plus_s,meta_plus_m,meta_plus_s,NaN
9630,medycyna,witam : ) mój maż ma bardzo poważny problem z ...,meta_zero,meta_zero,meta_zero,NaN
9631,medycyna,Jest dobrym ginekologiem bynajmniej takie słys...,meta_amb,meta_amb,NaN,meta_minus_s

In [13]:
annotators = ['super', 'a', 'e', 'k']
pairs = [[annotators[i], annotators[j]] for i in range(len(annotators)) for j in range(i + 1, len(annotators))]
pairs

[['super', 'a'],
 ['super', 'e'],
 ['super', 'k'],
 ['a', 'e'],
 ['a', 'k'],
 ['e', 'k']]

In [14]:
for pair in pairs:
    columns = zdania[pair].dropna()
    print(cohen_kappa_score(columns[pair[0]], columns[pair[1]]))

0.8425413961933904
0.9144596452221798
0.9163758130599683
0.7876418822931861
0.7511360855789728
1.0

In [18]:
zdania[pairs[-1]].dropna()

               e          k
1770      z_zero     z_zero
2578   z_minus_m  z_minus_m
4519      z_zero     z_zero
5226   z_minus_m  z_minus_m
6352      z_zero     z_zero
16318  z_minus_m  z_minus_m
37932   z_plus_m   z_plus_m
49316     z_zero     z_zero
51268     z_zero     z_zero
56713     z_zero     z_zero
60687     z_zero     z_zero
61275     z_zero     z_zero

In [20]:
for pair in pairs:
    columns = meta[pair].dropna()
    print(cohen_kappa_score(columns[pair[0]], columns[pair[1]]))

0.841610343202183
0.8619157313216369
0.8618052902164884
0.7123140150683738
0.7580248253380194
0.5023003723624327

In [16]:
columns = OrdinalEncoder().fit_transform(zdania[annotators])
krippendorff.alpha(reliability_data=columns.T)

0.8018978836994523

In [17]:
columns = OrdinalEncoder().fit_transform(meta[annotators])
krippendorff.alpha(reliability_data=columns.T)

0.8259639267073995